- name: ensure python development library headers are installed
  apt: name=python3-dev state=latest
  sudo: yes

- name: ensure python setup-tools is installed
  apt: name=python3-setuptools state=present
  sudo: yes